### ISSUE TITLE
App crashes when go in onPause(), java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 20195964 bytes

### ISSUE THREAD

**Issue by harshgaba** [IsseiAoki/SimpleCropView#101]
Android version N,

 compileSdkVersion 25
    buildToolsVersion '24.0.3'

  minSdkVersion 17
        targetSdkVersion 25 

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 20195964 bytes
                                                                                      at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3776)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                                   Caused by: android.os.TransactionTooLargeException: data parcel size 20195964 bytes
                                                                                      at android.os.BinderProxy.transactNative(Native Method)
                                                                                      at android.os.BinderProxy.transact(Binder.java:615)
                                                                                      at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3700)
                                                                                      at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3768)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:154) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6123) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by shuttertorture** [comment]
Same here. Due to the changes in Android N, the system has the freedom to reject bigger parcels when instance state is saved.

I'd suggest not parcelling the image bitmap but to save it to a temporary file instead.

**Comment by T-Tenma** [comment]
hey, just try this:
  ```
  @Override
    protected void onPause() {
        mCropImageView.setImageBitmap(null);
        super.onPause();
    }

```
and load the image again when go in onResume().

**Comment by Hamid95** [comment]
@T-Tenma nice

**Comment by IsseiAoki** [comment]
In the new version, CropImageView does not save bitmap internally . Please use the version 1.1.5 and see also new sample.
