### ISSUE TITLE
Can't save cropped image, UnsupportedOperationException

### ISSUE THREAD

**Issue by AlexEvtushik** [IsseiAoki/SimpleCropView#113]
java.lang.UnsupportedOperationException
                                                                    at java.util.AbstractList.add(AbstractList.java:404)
                                                                    at java.util.AbstractList.add(AbstractList.java:425)
                                                                    at com.isseiaoki.simplecropview.util.Utils.copyExifInfo(Utils.java:85)
                                                                    at com.isseiaoki.simplecropview.CropImageView.saveImage(CropImageView.java:1316)
                                                                    at com.isseiaoki.simplecropview.CropImageView.access$2100(CropImageView.java:58)
                                                                    at com.isseiaoki.simplecropview.CropImageView$17.call(CropImageView.java:1861)
                                                                    at com.isseiaoki.simplecropview.CropImageView$17.call(CropImageView.java:1858)
                                                                    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)

I catch this Exception when tried to save image, my code:
```
mCropView.crop(mCropView.getSourceUri())
                    .executeAsSingle()
                    .flatMap(bitmap -> {
                        Timber.d("On crop, image size: %dx%d", bitmap.getWidth(), bitmap.getHeight());
                        return mCropView.save(bitmap)
                                .executeAsSingle(saveUri);
                    })
                    .subscribeOn(Schedulers.newThread())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(uri -> {
                        Timber.d("On Crop, croppedPhotoUri: %s", uri);
                        dismiss();
                    }, throwable -> Timber.e(throwable));
```

How can I resolve this issue ?

**Comment by IsseiAoki** [comment]
Oh...I will fix it ASAP.

**Comment by IsseiAoki** [comment]
@AlexEvtushik 
Could you tell me your OS version?

**Comment by AlexEvtushik** [comment]
@IsseiAoki Android 6.0.1

**Comment by IsseiAoki** [comment]
@AlexEvtushik 
I have fixed the bug and released new version.
Please try version 1.1.6 : )

**Comment by AlexEvtushik** [comment]
@IsseiAoki now it works like a charm, thanks a lot!
