### ISSUE TITLE
Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference

### ISSUE THREAD

**Issue by dev-hussein** [IsseiAoki/SimpleCropView#141]
@igreenwood 
This crash when try to rotate image.
at com.isseiaoki.simplecropview.CropImageView.rotateImage(CropImageView.java:1633)
at com.isseiaoki.simplecropview.CropImageView.rotateImage(CropImageView.java:1594)
at com.isseiaoki.simplecropview.CropImageView.calcScale(CropImageView.java:542)

Please check first if getDrawable != null.

Testes devices.
- Samsung -> SM-N950F -> Android 8.0.0
- Xiaomi -> Redmi Note 5 -> Android 8.1.0

**Comment by tawhidkuet04** [comment]
how to handle this issue ? any suggestion
