### ISSUE TITLE
Unmarshalling unknown type code 51 at offset 400

### ISSUE THREAD

**Issue by sukrua** [IsseiAoki/SimpleCropView#17]
Hi,

We are getting an error like :

java.lang.RuntimeException: Unable to start activity ComponentInfo{....CropImageActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@41b317a0: Unmarshalling unknown type code 51 at offset 400
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2329)
            at android.app.ActivityThread.access$800(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5214)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@41b317a0: Unmarshalling unknown type code 51 at offset 400
            at android.os.Parcel.readValue(Parcel.java:2092)
            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2396)
            at android.os.Parcel.readSparseArray(Parcel.java:1747)
            at android.os.Parcel.readValue(Parcel.java:2082)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2329)
            at android.os.Bundle.unparcel(Bundle.java:249)
            at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
            at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1745)
            at android.app.Activity.onRestoreInstanceState(Activity.java:944)
            at android.app.Activity.performRestoreInstanceState(Activity.java:916)
            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2329)
            at android.app.ActivityThread.access$800(ActivityThread.java:145)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5214)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:814)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:630)
            at dalvik.system.NativeStart.main(Native Method)

Can you help me? 

Thanks

**Comment by shuttertorture** [comment]
Same here. However, the problem only shows up when activity gets recycled / on deep sleep.

Can be fixed easily by adding the static CREATOR, which is missing currently. I'm going to do a pull request.

**Comment by IsseiAoki** [comment]
Thank you @shuttertorture 

Your PR merged in version 1.0.11.
