### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ThunderRoid** [IsseiAoki/SimpleCropView#21]
When trying to load a camera image from my Galaxy s6, the app force closes.

at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:527)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:599)
at android.provider.MediaStore$Images$Media.getBitmap(MediaStore.java:724)
at com.shifat.cropandupload.MainActivity.onActivityResult(MainActivity.java:66)
at android.app.Activity.dispatchActivityResult(Activity.java:5192)

**Comment by Dona278** [comment]
Read these documents, you should fix it
http://developer.android.com/training/displaying-bitmaps/load-bitmap.html
http://developer.android.com/training/camera/photobasics.html
