### ISSUE TITLE
ClassCastException ColorDrawable cannot be cast to BitmapDrawable

### ISSUE THREAD

**Issue by akonior** [IsseiAoki/SimpleCropView#31]
```
java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
                                                                           at com.isseiaoki.simplecropview.CropImageView.getBitmap(CropImageView.java:924)
                                                                           at com.isseiaoki.simplecropview.CropImageView.setImageResource(CropImageView.java:964)
```

**Comment by akonior** [comment]
I have this code to clear CropImageView
```
cropImageView.setImageResource(android.R.color.transparent);
```

**Comment by IsseiAoki** [comment]
Hi,

I fixed the bug related to drawable. 
Please use version 1.0.13 : )

**Comment by akonior** [comment]
Thx a lot!
