### ISSUE TITLE
unfortunatley stopped

### ISSUE THREAD

**Issue by altaf2892** [IsseiAoki/SimpleCropView#72]
**i just have implemented SimpleCropView lib to my App It's Working perfect BUt  when cropped image and set it to ImageView and i just pressed Home Button Of MObile-Phone..Application sudden crashed with below mentioned logcate**
` java.lang.IllegalStateException: Can't parcel a recycled bitmap
                                                                                      at android.graphics.Bitmap.checkRecycled(Bitmap.java:354)
                                                                                      at android.graphics.Bitmap.writeToParcel(Bitmap.java:1479)
                                                                                      at android.os.Parcel.writeParcelable(Parcel.java:1285)
                                                                                      at com.isseiaoki.simplecropview.CropImageView$SavedState.writeToParcel(CropImageView.java:2185)
                                                                                      at android.os.Parcel.writeParcelable(Parcel.java:1285)
                                                                                      at android.os.Parcel.writeValue(Parcel.java:1204)
                                                                                      at android.os.Parcel.writeSparseArray(Parcel.java:693)
                                                                                      at android.os.Parcel.writeValue(Parcel.java:1229)
                                                                                      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
                                                                                      at android.os.Bundle.writeToParcel(Bundle.java:1692)
                                                                                      at android.os.Parcel.writeBundle(Parcel.java:636)
                                                                                      at android.os.Parcel.writeValue(Parcel.java:1201)
                                                                                      at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
                                                                                      at android.os.Bundle.writeToParcel(Bundle.java:1692)
                                                                                      at android.os.Parcel.writeBundle(Parcel.java:636)
                                                                                      at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2902)
                                                                                      at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3249)
                                                                                      at android.os.Handler.handleCallback(Handler.java:733)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:149)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
                                                                                      at dalvik.system.NativeStart.main(Native Method)
`

**now how to deal with this issue**

**Comment by IsseiAoki** [comment]
Hi,

What version do you use?

I have fixed the bug.
https://github.com/IsseiAoki/SimpleCropView/releases/tag/v1.1.3
 
If you use the version 1.1.3 or later, I must fix the bug again.

**Comment by altaf2892** [comment]
i was using this compile 'com.isseiaoki:simplecropview:1.1.2'  so i just changed to compile 'com.isseiaoki:simplecropview:1.1.3' .. so will this new version fixed the problem ?

**Comment by IsseiAoki** [comment]
Yes. I have never seen the same bug in using 1.1.3 or later.
But latest version is 1.1.4. Please use the latest version if possible.
